version: '3.6'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXD_SESSION_LENGTH=${INFLUXD_SESSION_LENGTH}
      - TZ=America/Mexico_City
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/var/lib/influxdb2:/var/lib/influxdb2
      - ./influxdb/etc/influxdb2:/etc/influxdb2

  grafana:
    image: grafana/grafana-oss:latest-ubuntu
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GRAFANA_INSTALL_PLUGINS}
      - TZ=America/Mexico_City
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
  
  nodered:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    container_name: nodered
    restart: always
    depends_on:
      - influxdb
    environment: 
      - NODE_RED_USERNAME=${NODE_RED_USERNAME}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_CREDENTIAL_SECRET}
      - TZ=America/Mexico_City
    ports:
      - '1880:1880'
    volumes:
      - ./nodered/data:/data
      - ./certs:/certs

  mqtt:
    restart: always
    container_name: mqtt
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
      - ./certs:/mosquitto/certs
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - TZ=America/Mexico_City
    ports:
      - 8883:8883
 
volumes:
  grafana: